export const DEFAULT_ROLES = [
  { key: 'SUPER_ADMIN', name: 'System Administrator', description: 'Akses penuh tanpa batas ke semua modul dan konfigurasi.', isSystem: true },
  { key: 'HR_ADMIN', name: 'HR Manager / Admin', description: 'Mengelola karyawan, absensi, cuti, shift, dan laporan HR.', isSystem: true },
  { key: 'MANAGER', name: 'Line Manager', description: 'Persetujuan cuti/absensi tim dan melihat laporan tim.', isSystem: true },
  { key: 'EMPLOYEE', name: 'Standard Staff Employee', description: 'Akses portal mandiri cuti, absensi, dokumen, dan reward.', isSystem: true },
  { key: 'FINANCE', name: 'Financial Controller', description: 'Akses modul penggajian, penagihan billing, dan procurement.', isSystem: true },
] as const;

export const PERMISSION_MATRIX_MODULES = [
  { key: 'dashboard', label: 'Dashboard / Home Overview' },
  { key: 'attendance', label: 'Attendance (Logging & Tracker)' },
  { key: 'leave', label: 'Leave / Absences Hub' },
  { key: 'reward', label: 'Gamification Reward & Points' },
  { key: 'employee', label: 'Employee Management Directory' },
  { key: 'approval', label: 'Sequential Approvals Inbox' },
  { key: 'reporting', label: 'Reporting & Analytics Center' },
  { key: 'company', label: 'Company Details & Struct' },
  { key: 'billing', label: 'Billing / SaaS Subscription' },
  { key: 'settings', label: 'Global System Settings' },
  { key: 'user-access', label: 'User Access Matrix & Accounts' },
  { key: 'announcement', label: 'Announcements Board Feed' },
  { key: 'assets', label: 'Asset Management Checkouts' },
  { key: 'documents', label: 'Document Sharing Tree' },
  { key: 'org-chart', label: 'Organization Tree View' },
  { key: 'shift', label: 'Shift Scheduler Grid' },
  { key: 'visitor', label: 'Visitor Logs Checkin' },
  { key: 'procurement', label: 'Procurement Purchases PO' },
  { key: 'modules', label: 'Module Registry Control' },
] as const;

export const DEFAULT_PERMISSION_MATRIX: Record<string, string[]> = {
  dashboard: ['SUPER_ADMIN', 'HR_ADMIN', 'MANAGER', 'EMPLOYEE', 'FINANCE'],
  attendance: ['SUPER_ADMIN', 'HR_ADMIN', 'MANAGER', 'EMPLOYEE'],
  leave: ['SUPER_ADMIN', 'HR_ADMIN', 'MANAGER', 'EMPLOYEE'],
  reward: ['SUPER_ADMIN', 'HR_ADMIN', 'MANAGER', 'EMPLOYEE'],
  employee: ['SUPER_ADMIN', 'HR_ADMIN', 'MANAGER', 'EMPLOYEE'],
  approval: ['SUPER_ADMIN', 'HR_ADMIN', 'MANAGER', 'EMPLOYEE'],
  reporting: ['SUPER_ADMIN', 'HR_ADMIN', 'MANAGER', 'FINANCE'],
  company: ['SUPER_ADMIN', 'HR_ADMIN'],
  billing: ['SUPER_ADMIN', 'FINANCE'],
  settings: ['SUPER_ADMIN', 'HR_ADMIN'],
  'user-access': ['SUPER_ADMIN'],
  announcement: ['SUPER_ADMIN', 'HR_ADMIN', 'MANAGER', 'EMPLOYEE'],
  assets: ['SUPER_ADMIN', 'HR_ADMIN', 'EMPLOYEE'],
  documents: ['SUPER_ADMIN', 'HR_ADMIN', 'MANAGER', 'EMPLOYEE'],
  'org-chart': ['SUPER_ADMIN', 'HR_ADMIN', 'MANAGER', 'EMPLOYEE'],
  shift: ['SUPER_ADMIN', 'HR_ADMIN', 'MANAGER', 'EMPLOYEE'],
  visitor: ['SUPER_ADMIN', 'HR_ADMIN'],
  procurement: ['SUPER_ADMIN', 'HR_ADMIN', 'MANAGER', 'FINANCE'],
  modules: ['SUPER_ADMIN'],
};
